### ISSUE TITLE
[메인페이지, 마이페이지] 프로필 정보 오류

### ISSUE THREAD

**Issue by Leeeydia** [wldud7788/fire-spot#70]
@@메인 회원카드 정보와 
마이페이지 회원 카드 정보가 일치하지 않습니다
(프로필사진, 닉네임)

----

회원 프로필 사진이 다릅니다. 
메인 페이지 => 구글 계정 프사
마이페이지 => 우리 플랫폼에서 새로 등록된 프사

**Comment by pending-done** [comment]
해결했습니다.
